corpus_name: dundee
language: en

column_map:
  participant_id: ""
  sentence_id: ""
  word_id: ""
  word: ""
  first_fixation_duration: ""
  gaze_duration: ""
  go_past_time: ""
  total_reading_time: ""

optional_column_map:
  sentence_text: ""
  position_in_sentence: ""
  sentence_length: ""
  pos: ""
  is_content_word: ""

filters:
  min_rt: 50
  max_first_fixation_duration: 800
  max_gaze_duration: 1500
  max_go_past_time: 5000
  max_total_reading_time: 8000
